Add a `--commit` option to automatically commit fixes
laravel/pint pull request #233
Opened 2023-11-28 21:54 UTC by caendesilva

## Abstract

This pull request adds a `--commit` option to the Pint command, making it easy to commit style changes to Git!

### Development

I tried to match the output formatting and code style to the rest of the codebase, as best I could. The implementation could probably be simplified, instead of using the new action class.

#### Tests

I have not yet added tests, as I first want to know if this is of interest to the maintainers. When given the go-ahead I'm more than happy to add them.

### Screenshots

**Success:**

![image](https://github.com/caendesilva/temp/assets/95144705/87dc0cb5-62d0-4e0b-8897-506830890503)

**Nothing to change:**

![image](https://github.com/caendesilva/temp/assets/95144705/6e352a4c-0278-4870-bd89-0172c386084b)

**Error:**

![image](https://github.com/caendesilva/temp/assets/95144705/a0e6d268-fb96-49b5-8d3c-610505515590)

2023-11-29 09:18 UTC, nunomaduro requested changes

2023-11-29 09:18 UTC, nunomaduro commented on app/Actions/GitCommitter.php
> +    protected function makeCommit(array $files)
I would call this method `commit`.

2023-11-29 09:18 UTC, nunomaduro commented on app/Actions/GitCommitter.php
> +     * @param  array<string>  $files
`array<int, string>`

2023-11-29 09:18 UTC, nunomaduro commented on app/Actions/GitCommitter.php
> +                    <span class="text-green-500">No changes to commit!</span>
`Nothing to commit, working tree clean.`

2023-11-29 09:18 UTC, nunomaduro commented on app/Actions/GitCommitter.php
> +                    <span class="text-green-500">No changes to commit!</span>
Can you use the regular "INFO" message that we usually use?

2023-11-29 09:18 UTC, nunomaduro commented on app/Actions/GitCommitter.php
> +                    <span class="px-2 bg-red text-white uppercase font-bold mr-1">Error:</span>
Can you use the regular "ERROR" message that we usually use?

2023-11-29 09:18 UTC, nunomaduro commented on app/Actions/GitCommitter.php
> +                <span class="text-green-500">Changes committed successfully!</span>
Can you use the regular "INFO" message that we usually use?

2023-11-29 09:18 UTC, nunomaduro commented on app/Actions/GitCommitter.php
> +                <span class="text-green-500">Changes committed successfully!</span>
I would expect here something like this: `1 file changed, 2 insertions(+)`.

2023-11-29 09:21 UTC, caendesilva commented
Thanks for reviewing @nunomaduro, I really appreciate it! I'm a bit busy today but will fix everything as soon as I can! 🚀

2023-11-30 22:08 UTC, caendesilva commented
Okay, all issues you brought up should be resolved, along with added tests!

2023-12-20 17:29 UTC, nunomaduro commented
@taylorotwell @caendesilva I've reviewed and applied a few changes. Wondering if we should also `push` the changes?

2023-12-20 17:59 UTC, caendesilva commented
> @taylorotwell @caendesilva I've reviewed and applied a few changes. Wondering if we should also `push` the changes?

By adding another `--push` flag, or should `--commit` also push? Because I'm not sure the latter is good as it may violate the principle of least astonishment, though I could also be reading your message wrong?

2023-12-21 14:09 UTC, taylorotwell commented
Personally don't think we need this flag at the moment. I'm not a big fan of these types of things as they do tend to lead to feature creep.

2023-12-21 14:09 UTC, closed without merging

2023-12-21 14:45 UTC, caendesilva commented
> Personally don't think we need this flag at the moment. I'm not a big fan of these types of things as they do tend to lead to feature creep.

@nunomaduro What do you think? I fully understand Taylor's hesitation regarding feature creep, though I would personally argue that the feature is quite light (and could be simplified further), but adds a lot of value as it speeds up workflows even more.